name: CustomItemDemo
version: '${version}'
description: demo Project
main: com.tinyshellzz.customitemdemo.CustomItemDemo
api-version: '1.20.6'
load: POSTWORLD
softdepend: [ Vault, LuckPerms, PlaceholderAPI ]
authors: [ Tinyshellzz ]
folia-supported: true
website: https://github.com/
